# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChiselCut' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for ChiselCut
  source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 4.0'

  target 'ChiselCutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChiselCutUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
